# Generated by Django 5.1.5 on 2025-03-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Name', models.CharField(default='null', max_length=255)),
                ('Rank', models.CharField(default='null', max_length=255)),
                ('Designation', models.CharField(default='null', max_length=255)),
                ('Course', models.CharField(default='null', max_length=255, unique=True)),
                ('Role', models.CharField(default='null', max_length=255)),
                ('Address', models.CharField(default='null', max_length=255)),
                ('College', models.CharField(default='null', max_length=255)),
                ('Number', models.CharField(default='null', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('AvgGrade', models.FloatField()),
                ('AvgCet', models.FloatField()),
                ('TotalScore', models.FloatField()),
                ('CourseDescription', models.CharField(max_length=500)),
                ('Logo', models.CharField(default='img/png-clipart-computer-icons-error-information-error-angle-triangle-thumbnail-removebg-preview copy.png', max_length=500)),
                ('reason', models.CharField(max_length=500, null=True)),
                ('Category', models.FloatField(default=0)),
                ('MainLogo', models.CharField(default='img/png-clipart-computer-icons-error-information-error-angle-triangle-thumbnail-removebg-preview copy.png', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.FloatField(default=0)),
                ('AvgGrade', models.FloatField(default=0)),
                ('AvgCet', models.FloatField(default=0)),
                ('TotalScore', models.FloatField(default=0)),
                ('PersonalityScore', models.FloatField(default=0)),
                ('courseName', models.CharField(default='General', max_length=255)),
                ('Question', models.TextField(default='null')),
                ('Category', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('AvgGrade', models.FloatField()),
                ('AvgCet', models.FloatField()),
                ('Number', models.CharField(max_length=20)),
                ('ApplicationNo', models.CharField(default=0, max_length=50)),
                ('Address', models.TextField()),
                ('Course', models.CharField(max_length=255)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('Year', models.IntegerField(default=0)),
                ('EnglishProficiency', models.IntegerField(default=0)),
                ('ReadingComprehension', models.IntegerField(default=0)),
                ('ScienceProcessSkills', models.IntegerField(default=0)),
                ('MathematicalSkills', models.IntegerField(default=0)),
                ('AbstractLogicThinkingSkills', models.IntegerField(default=0)),
                ('CetPicture', models.ImageField(blank=True, default='null', null=True, upload_to='cet_results/')),
                ('GradePicture', models.ImageField(blank=True, default='null', null=True, upload_to='grades/')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('otp', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('courseName', models.CharField(default='General', max_length=255)),
                ('Percentage', models.FloatField(default=0)),
                ('Category', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.FloatField()),
                ('Year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvgGrade', models.FloatField(default=0)),
                ('AvgCet', models.FloatField(default=0)),
                ('StudentID', models.FloatField()),
                ('question', models.CharField(max_length=500)),
                ('response', models.FloatField()),
                ('courseName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CetAvgPercentage', models.FloatField(default=0)),
                ('GradeAvgPercentage', models.FloatField(default=0)),
                ('PersonalityPercentage', models.FloatField(default=0)),
            ],
        ),
    ]
